### ISSUE TITLE
Namespace components

### ISSUE THREAD

**Issue by mediafinger** [PhlexyUI/phlexy_ui#1]
# The issue without namespace

**UPDATE: Seems like there is a chance to use the namespaces and keep the short-form. Likely all depends on where / if `PhlexyUI` and the `Phlex::Kit` is included - will update this, when we implemented a working version.**

---

Our app is using Phlex 2.0 and bundles the main branch of this gem. When we setup PhlexyUI as described in the readme, we encountered the issue, that our own components could no longer be called by the short-form (e.g. `TabNav do ...`), but had to be called in the long `render Components::TabNav.new do...` form.

We started looking for a way to keep using the short-for, but due to the current limitations of `Phlex::Kit` there seems to be no way to easily add a namespace to components **and** use the short from (e.g. `PhlexyUI::Card do ...`). So the best we came up with, was to `include PhlexyUI` inside of a view - and then we could use the short-form for the PhlexyUI _and_ our custom components. Though we had two issues with that:

1. there were name clashes, as we e.g. had defined a `Card` component already (unclear which one would be used then)
2. we didn't like that it was impossible to tell, where the used component is defined

## Our originally preferred solution

We wanted to wrap all the PhlexyUI components in a module (as namespace) to be then able to call: e.g. `Namespace::Card do ...`.

We've seen the **prefix** part in the documentation and would wish a similar mechanism not only for the CSS-classes, but for calling the components, to be able to use this components library besides others and our custom ones.

We tried to inherit custom components from PhlexyUI components - for namespacing, but also to be able to have slightly different versions. Unfortunately this also fails due to how `Phlex::Kit` is implemented. (At least the PhlexyUI configuration allows to adapt the components - but it does not allow to keep separate versions.)

## Our workaround _(or probably permanent solution)_

We removed the `include PhlexyUI` directive and instead in `Components::Base` (or if you prefer: `ApplicationComponents`) we generate now methods to have _a_ short-form to use the components:

```ruby
    # make the PhlexyUI / DaisyUI components available in all views via `daisy_component_name` methods
    # names taken from https://daisyui.com/components - PhlexyUI is not complete yet and might use different names
    #
    def self.define_daisy_methods
      %w[accordion alert artboard avatar badge bottom_navigation breadcrumbs browser_mockup button card carousel
         chat_bubble checkbox code_mockup collapse countdown diff divider drawer dropdown file_input footer hero
         indicator join kbd link loading mask menu modal navbar pagination phone_mockup progress radial_progress
         radio range_slider rating select skeleton stack stat steps swap table tabs text_input textarea
         theme_controller timeline toast toggle tooltipwindow_mockup
       ].each do |component_name|
        define_method(:"daisy_#{component_name}") do |*args, **options, &block|
          render "PhlexyUI::#{component_name.titleize.split.join}".constantize.new(*args, **options, &block)
        end
      end
    end
``` 

Which allows us to use methods like `daisy_card` (instead of `Card`). These methods pass all the arguments and the block to ` render PhlexyUI::Card.new` (replace Card my the name of any method) so we should always be on the safe side.

> We then did the same for our custom components with a different prefix, to avoid using the short-form Phlex::Kit offers (which seems to come with too man limitations) while still having _a_ short form.

This solved at least the _short-form_ issue for us in a satisfying way - which uses much less "magic" than Phlex::Kit.

---

_Anyhow, thanks for reading my ramblings. Maybe it will serve as an inspiration to a solution I don't see yet. And thanks for implementing DaisyUI in Phlex!_

**Comment by mediafinger** [comment]
Closing this issue, as the only thing we apparently had to do to allow us to use this gem's components with the `PhlexyUI::` namespace - and our custom components directly, without a namespace - was not **not include** `PhlexyUI` in any of the Phlex components classes.

It doesn't answer the other questions about inheritance or custom namespaces (e.g. one that is easier to type than "PhlexyUI" 😉 ) or reusing the gem's components in customized components. But those all seem to boil down to be asked to Phlex and about the `Phlex::Kit`.

**Comment by davidalejandroaguilar** [comment]
Hey @mediafinger, thanks for the detailed issue. Glad to see someone using it in the wild and that you found a solution for your problem. Here are my thoughts:

### Phlex Kits and namespacing

You now know this, but I'm writing this down in case someone else reads it.

So the only reason we `include PhlexyUI` is to avoid the namespace, e.g, to use:

```rb
class MyView < ApplicationComponent
  def view_template
    Button :primary do
    end
  end
end
```

Instead of:

```rb
class MyView < ApplicationComponent
  def view_template
    PhlexyUI::Button :primary do
    end
  end
end
```

But if you already have your own components with the same name, and you're including the module for those custom components in `ApplicationComponent` , including `PhlexyUI` in `ApplicationComponent` will lead to name clashes. I'm updating the documentation to mention this and thank you for bringing this up.

By not including `PhlexyUI` in `ApplicationComponent`, you can now:

* Use namespaced PhlexyUI components, e.g. `PhlexyUI::Button do`
* Use your own non-namespaced components, e.g. `Button do`

### Custom wrapping namespace

So I don't think you need a workaround for this, right?

>We wanted to wrap all the PhlexyUI components in a module (as namespace) to be then able to call: e.g. Namespace::Card do ....

Though if you do, this can be roughly achieved like this (this could probably be done dynamically):

```rb
# app/views/components/my_namespace.rb
module MyNamespace
  extend Phlex::Kit
end

# app/views/components/application_component.rb
class ApplicationComponent < Phlex::HTML
  # To avoid name clashing:
  # Don't include MyNamespace
  # Don't include PhlexyUI
end

# app/views/components/my_namespace/button.rb
module MyNamespace
  class Button < ApplicationComponent
    def initialize(*args, **kwargs)
      @args = args
      @kwargs = kwargs
    end

    def view_template
      PhlexyUI::Button(*@args, **@kwargs) do
        yield
      end
    end
  end
end

# app/views/my_view.rb
class MyView < ApplicationComponent
  def view_template
    MyNamespace::Button :primary do
    end
  end
end
```

Which is basically like using PhlexyUI in your own components, just completely delegating and not customizing it at all.

### Configurable namespacing

>We've seen the prefix part in the documentation and would wish a similar mechanism not only for the CSS-classes, but for calling the components, to be able to use this components library besides others and our custom ones.
>
> [...] custom namespaces (e.g. one that is easier to type than "PhlexyUI" 😉 ) [...]

So now that you're no longer including `PhlexyUI` in `ApplicationComponent`, you have to use the long-ish form of `PhlexyUI:Button do ...`, but you're thinking a shorter namespace would look better, right?

I might be able to look into this, but since you're using your own custom components and only using PhlexyUI to help build them, the rest of your app will use your short custom components form, e.g. `Button`, essentially hiding the `PhlexyUI` namespace, so I wonder if this is needed in this case?

In other words: 

* If you don't have your own custom components using Phlex Kit that you're including in `ApplicationComponent`, then you can just `include PhlexyUI` and you'll avoid having to write the `PhlexyUI` namespace.
* If you have custom components using Phlex Kit that you're including in `ApplicationComponent`, and using PhlexyUI inside of them, then that's kind of an "implementation detail" and the `PhlexyUI` namespace will still be hidden.

### Inheritance

I also don't think you need this anymore, right?

>We tried to inherit custom components from PhlexyUI components - for namespacing, but also to be able to have slightly different versions. Unfortunately this also fails due to how Phlex::Kit is implemented. (At least the PhlexyUI configuration allows to adapt the components - but it does not allow to keep separate versions.)

Though just wanted to mention that, at least on pre 2.0, inheriting from a PhlexUI component is possible. You can render them using both the short and long form:

```rb
# app/views/components/my_button.rb
class MyButton < PhlexyUI::Button
  def view_template
    Button :primary do
      plain "My button"
      yield
    end
  end
end

# app/views/components/testing/my_other_button.rb
module Testing
  class MyOtherButton < PhlexyUI::Button
    def view_template
      Button :primary do
        plain "My other button"
        yield
      end
    end
  end
end

# app/views/components/testing.rb
module Testing
  extend Phlex::Kit
end

# app/views/components/application_component.rb
class ApplicationComponent < Phlex::HTML
  include PhlexyUI
  include Testing
end

# app/views/examples/show_view.rb
render MyButton.new do
  "yield my button"
end

MyOtherButton do
  "yield my other button"
end
```

Though I wonder what your customization needs are that make you want to inherit directly from the PhlexyUI component instead of:

* Passing classes via `class:` directly when rendering them.
* Using [custom modifiers](https://phlexyui.com/docs/configuration).
* Using your own component, e.g.

```rb
class MyButton < ApplicationComponent
  def view_template
    # Using PhlexyUI's button
    Button :primary do
    end

   span do
      "Some span that always renders next to MyButton?"
   end
  end
end
```

I think the latter would address this part you mentioned?:

> reusing the gem's components in customized components
---

Let me know if I'm missing anything, and thanks again for your thoughtful message.

**Comment by mediafinger** [comment]
Hello David and thank you for this detailed answer!

And yes, you are right, after _not including_ PhlexyUI all our issues have been solved.

> _(Though it was one of those issues where we had to sleep over it and I would have sworn we've tried this before without any luck...)_ 😆 

We can now use the short-form now for our own component`Card` and the PhlexyUI component `PhlexyUI::Card`.  
We also do inheritance now and can therefore create our own component based on PhlexyUI components. Our first use case was to inherit from `Drawer` to be able to add custom classes to its parts:

```ruby
module Components
  class Drawer < PhlexyUI::Drawer
    def view_template(&)
      options[:class] = "this custom classes could come from configuration #{options[:class]}"
      super
    end

    def toggle(**options, &)
      options[:class] = "for these classes we need inheritance #{options[:class]}"
      super
    end

    ...
```

... and to maybe add some extra logic into some components (e.g. a `turbo_frame_tag`).
